### ISSUE TITLE
error in catkin build

### ISSUE THREAD

**Issue by hmoyen** [SkyRats/sky_ws#2]
```
Errors     << mavros_msgs:make /home/lena/sky_ws/logs/mavros_msgs/build.make.000.log
Traceback (most recent call last):
  File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    genmsg.template_tools.generate_from_command_line_options(
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 93, in _generate_msg_from_file
    _generate_from_spec(input_file,
  File "/opt/ros/noetic/lib/python3/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True}).
AttributeError: module 'em' has no attribute 'RAW_OPT'
```

Then build fails

```
cd /home/lena/sky_ws/build/mavros_msgs; catkin build --get-env mavros_msgs | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................
Failed     << mavros_msgs:make                     [ Exited with code 2 ]      
Failed    <<< mavros_msgs                          [ 10.0 seconds ]            
Abandoned <<< mavros                               [ Unrelated job failed ]    
Abandoned <<< mavros_extras                        [ Unrelated job failed ]    
Abandoned <<< sky_sim                              [ Unrelated job failed ]    
Abandoned <<< sky_vision                           [ Unrelated job failed ]    
Abandoned <<< test_mavros                          [ Unrelated job failed ]    
Finished  <<< libmavconn                           [ 7.4 seconds ]             
[build] Summary: 3 of 9 packages succeeded.                                    
[build]   Ignored:   3 packages were skipped or are skiplisted.                
[build]   Warnings:  None.                                                     
[build]   Abandoned: 5 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 15.1 seconds total.                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.


```

**Comment by hmoyen** [comment]
@hfcaio suggested:

`pip uninstall empy`
`pip install empy==3.3.4`

and build suceeded
